add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_types.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/queue_register.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_components.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_data_port.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/chopper.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/float_intake_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/float_outlet_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/pipeline_register_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/pool_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_types.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_data_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/count_down_register.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/count_up_register.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/delay_adjuster.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/delay_register.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/float_intake_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/float_outlet_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/pipeline_register.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/syncronizer_input_pending_register.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/unrolled_loop_counter.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_types.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_components.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_atrb_generator.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/pump/pump_components.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/pump/pump_control_register.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_master_address_channel_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_master_transfer_queue.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_register_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_register_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/pool_intake_port.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/queue_arbiter.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/queue_receiver.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_components.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_int_adder.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_parameter_buffer_reader.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_parameter_buffer_writer.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_buffer_bank_memory_reader.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_buffer_bank_memory_writer.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_buffer_intake_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_buffer_outlet_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/pump/pump_controller_intake_side.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/pump/pump_controller_outlet_side.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/pump/pump_flow_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_master_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_master_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/axi4/axi4_register_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/queue_arbiter_integer_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/queue_arbiter_one_hot_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/sdpram_xilinx_ultrascale_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_int_accumulator.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_int_adder_tree.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/convolution/convolution_parameter_buffer.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_slice_master_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_slice_range_generator.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_buffer_intake.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_buffer_outlet.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_channel_reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/image/image_stream_generator_with_padding.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/pump/pump_stream_intake_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/pump/pump_stream_outlet_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../qconv-strip-vhdl/PipeWork/src/components/register_access_decoder.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_params.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_apply_thresholds.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_components.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_multiplier.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_in_data_buffer.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_k_data_buffer.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_th_data_buffer.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_controller.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_core.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_in_data_axi_reader.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_k_data_axi_reader.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_out_data_axi_writer.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_registers.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_th_data_axi_reader.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_axi_core.vhd
add_vhdl_file sources_1 QCONV ../qconv-strip-vhdl/src/main/vhdl/qconv_strip_axi_ultrascale.vhd
